- id: pytest-super-setup
  name: Check setUp/tearDown methods
  entry: pytest-super-hooks
  language: python
  types: [python]

- id: pytest-super-setup-fix
  name: Fix setUp/tearDown methods
  entry: pytest-super-hooks --fix
  language: python
  types: [python]
